### ISSUE TITLE
error import mabed.stats as st

### ISSUE THREAD

**Issue by Mustyy** [AdrienGuille/pyMABED#1]
When I try to run detect_events.py I end up getting an error
ImportError: No module named stats

I installed all the dependencies too

**Comment by AdrienGuille** [comment]
Hi Mustyy,

Could you please provide more details (_e.g._ OS, Python version, the exact command)?

Adrien

**Comment by Mustyy** [comment]
Hey Adrien
I solved it
It was regarding the python version
Now I just get an error 

text_column_index = header.index('Text')
ValueError: 'Text' is not in list

**Comment by Mustyy** [comment]
The problem is my tweets are in a json file and not in a csv
